package com.clownteam.collection_datasource.models.get_collection

import com.clownteam.collection_datasource.models.CourseCollectionResponseItem

class GetCollectionResponse : CourseCollectionResponseItem()