package com.clownteam.collection_datasource.models.get_collections

import com.clownteam.collection_datasource.models.CourseCollectionResponseItem
import com.clownteam.core.network.PaginationResponse

class GetCollectionsResponse: PaginationResponse<CourseCollectionResponseItem>()
